name: Machine Learning Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        cd day5/演習3
        python -m pytest tests/test_data.py tests/test_model.py -v
        
    - name: Generate test report
      if: always()
      run: |
        cd day5/演習3
        echo "# テスト実行結果" > test_report.md
        echo "実行日時: $(date)" >> test_report.md
        echo "## テスト結果サマリー" >> test_report.md
        python -m pytest tests/test_data.py tests/test_model.py -v --no-header --no-summary | grep -E "(PASSED|FAILED|SKIPPED)" >> test_report.md
        
    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: day5/演習3/test_report.md 